server:
  port: 6669


spring:
  application:
    name: blog-link

  datasource:
    url: jdbc:mysql://localhost:3306/blog_link?serverTimezone=Asia/Shanghai&useSSL=false
    hikari:
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2MB          # 文件上传最大内存
      max-request-size: 5MB

  cloud:
    nacos:
      server-addr: 1.117.70.65:8848
      username: nacos
      password: nacos_start!!!
      config:
        group: PROPERTIES_GROUP
        shared-configs[0]:
          data-id: application.yml
          refresh: true
  config:
    import:
      - optional:nacos:application.yml


#dubbo:
#  protocol:
#    port: -1
#    name: dubbo
#  registry:
#    address: nacos://${spring.cloud.nacos.server-addr}
#    username: ${spring.cloud.nacos.discovery.username}
#    password: ${spring.cloud.nacos.discovery.password}
#    parameters:
#      namespace: dubbo
#      group: dubbo
#  application:
#    qos-enable: false
#  consumer:
#    check: false

