service:
  article: lb://blog-article
  user: lb://blog-user
  comment: lb://blog-comment
  link: lb://blog-link

server:
  port: 7777

spring:
  application:
    name: blog-gateway

  cloud:
    nacos:
      server-addr: 192.168.10.10:8848
      discovery:
        username: nacos
        password: nacos
        group: SEATA_GROUP

    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': # 表示对所有的请求
            allowedOriginPatterns: '*'
            allowedMethods: ['GET', 'POST', 'PUT', 'DELETE']
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: article_route
          uri: ${service.article}
          predicates:
            - Path=/article/**
        - id: category_route
          uri: ${service.article}
          predicates:
            - Path=/category/**

        - id: user_route
          uri: ${service.user}
          predicates:
            - Path=/user/**
        - id: login_route
          uri: ${service.user}
          predicates:
            - Path=/login
        - id: logout_route
          uri: ${service.user}
          predicates:
            - Path=/logout
        - id: upload_route
          uri: ${service.user}
          predicates:
            - Path=/upload

        - id: comment_route
          uri: ${service.comment}
          predicates:
            - Path=/comment/**

        - id: link_route
          uri: ${service.link}
          predicates:
            - Path=/link/**

      # 将重复的请求头删除，网关和后端的跨域导致两个了，删掉一个
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
